define([], function() {
  return {
    "PropertyPaneDescription": "Render a SharePoint list as Phillips-branded cards or rows, optionally with a tab strip driven by list views.",
    "ContentGroupName": "Content",
    "OverlayGroupName": "Card overlay",
    "SectionTitleFieldLabel": "Section title",
    "ListFieldLabel": "List",
    "ListEmptyLabel": "Lists load from the current site when the pane opens.",
    "LayoutFieldLabel": "Layout",
    "LayoutGalleryOptionLabel": "Gallery cards",
    "LayoutTableOptionLabel": "Table rows",
    "ShowTabsFieldLabel": "Show tabs",
    "ViewFieldLabel": "View",
    "TabCountFieldLabel": "Number of tabs",
    "TabsFieldLabel": "Tabs",
    "TabsPanelHeader": "Configure tabs",
    "TabsManageButtonLabel": "Edit tabs",
    "TabLabelColumnLabel": "Label",
    "TabViewColumnLabel": "View",
    "TabViewEmptyOptionLabel": "Select a view",
    "SeeAllUrlFieldLabel": "See All link (URL)",
    "ShowOverlayFieldLabel": "Show card overlay (gallery layout only)",
    "OverlaySourceFieldLabel": "Source field",
    "OverlayLabelTemplateFieldLabel": "Label template (use {value})",
    "OverlayPositionFieldLabel": "Position",
    "OverlayPositionTopLeftLabel": "Top-left",
    "OverlayPositionTopRightLabel": "Top-right",
    "OverlayPositionBottomLeftLabel": "Bottom-left",
    "OverlayPositionBottomRightLabel": "Bottom-right",
    "EmptyStateMessage": "No items to display.",
    "ListNotConfiguredMessage": "Open the property pane to pick a list and configure tabs.",
    "TabNotConfiguredMessage": "Open the property pane to finish configuring this tab.",
    "LoadErrorMessage": "Couldn't load items.",
    "SeeAllLinkLabel": "SEE ALL"
  }
});
